Support eval with custom dataset
Megvii-BaseDetection/YOLOX pull request #1131
Opened 2022-02-17 19:13 UTC by ArMaxik

Eval extract class names from dataset. It allows to evaluate models on datasets with classes different from coco.

2022-02-17 19:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Megvii-BaseDetection/YOLOX?pullRequest=1131) it.</sub>

2022-02-18 03:37 UTC, FateScript requested changes

2022-02-18 03:37 UTC, FateScript commented on yolox/evaluators/coco_evaluator.py
> +            datasetCatsIds = list(cocoGt.cats.keys())
Plz use snake case name style in this PR, thx

2022-02-18 03:37 UTC, FateScript commented on yolox/evaluators/coco_evaluator.py
> +            datasetCatsNames = [cocoGt.cats[catId]['name'] for catId in sorted(datasetCatsIds)]
ditto

2022-02-18 03:38 UTC, FateScript commented
Thanks for contribution. You format check also failed, plz lint your code also @ArMaxik

2022-02-18 09:24 UTC, ArMaxik commented on yolox/evaluators/coco_evaluator.py
> +                per_class_AP_table_str = per_class_AP_table(cocoEval, class_names=cat_names)
Due to line lenght limits `per_class_AP_table_str ` var was added. Potentially it can be futher used for returning per_class AP/AR for fancy logging.

2022-02-21 02:52 UTC, FateScript commented
LGTM.

2022-02-21 02:52 UTC, FateScript approved these changes

2022-02-21 02:53 UTC, merged