Include demo for speeding up YOLOX with nebullvm inference accelerator
Megvii-BaseDetection/YOLOX pull request #1545
Opened 2022-10-25 15:44 UTC by emilecourthoud

This PR includes nebullvm among the tools for YOLOX deployment and optimization.

[nebullvm](https://github.com/nebuly-ai/nebullvm) is an open-source library designed to accelerate AI inference of deep learning models in a few lines of code. Nebullvm leverages state-of-the-art model optimization techniques such as deep learning compilers (TensorRT, Openvino, ONNX Runtime, TVM, TF Lite, DeepSparse, etc.), various quantization and compression strategies to achieve the maximum physically possible acceleration on the user's hardware.

During tests on various CPUs and GPUs and on YOLOX models of different sizes, nebullvm averaged a 2.2-fold acceleration in inference time.

2022-10-25 15:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1545) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1545) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Megvii-BaseDetection/YOLOX?pullRequest=1545) it.</sub>

2022-11-01 03:01 UTC, FateScript requested changes
PTAL @emilecourthoud

2022-11-01 03:01 UTC, FateScript commented on requirements.txt
> +nebullvm>=0.4.4
Plz move this to your README of nebullvm, thanks.

2022-11-01 12:54 UTC, emilecourthoud commented
Hi @FateScript, I updated the PR according to your suggestions.

2022-11-02 03:50 UTC, FateScript approved these changes

2022-11-02 03:51 UTC, FateScript commented
Well done @emilecourthoud :) Thanks for your contribution. LGTM.

2022-11-02 17:58 UTC, emilecourthoud commented
Hello @FateScript, I noticed that the check fails. I have not changed any requirements, could you please check if this is a problem with YOLOX test code?

2022-11-03 03:15 UTC, FateScript commented
@emilecourthoud Plz don't worry, I have fixed the workflow. I will rerun it.

2022-11-03 03:36 UTC, merged