Add sequence support for experiment options merge function #1613
Megvii-BaseDetection/YOLOX pull request #1614
Opened 2023-02-20 14:20 UTC by cansik

As mentioned in #1613 tuple and list arguments are not supported by the merge function. This PR adds support for both of them and even converts the values directly into the source format.

Example:

```
python tools/train.py -f myexperiment.py -d 1 -b 64 input_size "512, 512"
```

2023-02-20 14:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Megvii-BaseDetection/YOLOX?pullRequest=1614) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Megvii-BaseDetection/YOLOX?pullRequest=1614) it.</sub>

2023-02-28 12:30 UTC, FateScript commented
Thanks for your contribution @cansik  : ) https://github.com/Megvii-BaseDetection/YOLOX/pull/1618/files

2023-02-28 15:11 UTC, cansik commented
No worries, I have added the stripping of the brackets.

2023-03-01 02:49 UTC, FateScript requested changes
PTAL @cansik

2023-03-01 02:49 UTC, FateScript commented on yolox/exp/base_exp.py
> +                if isinstance(src_value, Sequence):
IMHO, `Sequence` is not suitable here. String type is also seqence, 
```python
isintance(src_value, (tuple, list))
```
might be better. WDYT?

2023-03-02 01:58 UTC, FateScript commented
Any update? @cansik

2023-03-02 12:17 UTC, FateScript approved these changes

2023-03-02 12:18 UTC, FateScript commented
LGTM.

2023-03-03 04:02 UTC, merged